### ISSUE TITLE
matlab code

### ISSUE THREAD

**Issue by sssongsshan** [BlackPianoCat/NonGaussianSurfaces#2]
Thank you very much for your code, your code is excellent. But may I have a look at the Matlab code?

**Comment by huliye123** [comment]
Hello, I have MATLAB code here, you can refer to it. This is my mailbox
huliye1833539020@gmail.com, please ask me for it.
[SRM.zip](https://github.com/user-attachments/files/15746076/SRM.zip)

**Comment by sssongsshan** [comment]
THANK YOU!!!

**Comment by BlackPianoCat** [comment]
You can look in previous issues, I have uploaded the code. It is long time since I was working in this project. I remember that there is a problem with non-Gaussian surfaces in python, and my simulation produces outliers. I did not succeed to fix that, but you can try to do that. Please make a pull request in case that you will find solution to that.
